### ISSUE TITLE
Issue in init of motionclassifier

### ISSUE THREAD

**Issue by agunapal** [smellslikeml/YogAI#4]
Could you please clarify what this part of code is doing. There are no files with the prefix "motion_" in the models directory.

self.motion_path = sorted(glob('./models/motion_*'))[-1]
self.N = int(os.path.splitext(self.motion_path)[0].split('_')[-1])
self.motion_model = load_model(self.motion_path)

**Comment by ganeshmani** [comment]
i am facing the same problem. i guess it is referring to "motion.h5" with underscore in it.. "motion_.h5". Even if i am correcting that, i am getting some error in "self.N". 

``` Using TensorFlow backend.
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "demo.py", line 127, in <module>
    mC = motionClassifier()
  File "demo.py", line 29, in __init__
    self.N = int(os.path.splitext(self.motion_path)[0].split('_')[-1])
ValueError: invalid literal for int() with base 10: ''
```


@smellslikeml  can you help me with this.
<img width="530" alt="Screenshot 2019-10-06 at 8 46 41 PM" src="https://user-images.githubusercontent.com/17050715/66271385-055b4600-e87b-11e9-886b-341d75fc0e52.png">

**Comment by abhigoku10** [comment]
@agunapal @ganeshmani @smellslikeml  i am getting this error "UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 1: ordinal not in range(128)" when i run " python3 inference.py" on cpu

**Comment by smellslikeml** [comment]
@abhigoku10 have you trained your own model using the ```train.py``` script? Suspecting you may have tried running a pickled model that was trained on a different machine. I think you should delete that model (```models/classifier.sav```) and train your own so that it can be pickled and decoded correctly.

**Comment by abhigoku10** [comment]
@smellslikeml  i have not trained on my own , i am still running your example model for that only i am facing the issues

**Comment by smellslikeml** [comment]
@abhigoku10 
That model was a placeholder - I've deleted it to avoid confusion.
For the ```inference.py``` script to work, you need to train your own model using the ```preprocess.py``` script and then running the ```train.py``` script on your own directories of images. Then you will have your own ```models/classifier.sav``` pickled model to run on your device. 

The placeholder model doesn't work because pickled models can't be run on different machines from which they were created.
