### ISSUE TITLE
AttributeError: module 'tensorflow_core.contrib' has no attribute 'lite'

### ISSUE THREAD

**Issue by japita-se** [smellslikeml/YogAI#5]
On a fresh install:

python3 demo.py 
Using TensorFlow backend.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "demo.py", line 124, in <module>
    mC = motionClassifier()

  File "demo.py", line 19, in __init__
    self.interpreter = tf.contrib.lite.Interpreter(model_path=self.model_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/lazy_loader.py", line 63, in __getattr__
    return getattr(module, item)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 51, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorflow_core.contrib' has no attribute 'lite'

**Comment by gohjiayi** [comment]
I encountered this as well and was able to run it by removing contrib. Instead of `self.interpreter = tf.contrib.lite.Interpreter(model_path=self.model_path)` I have `self.interpreter = tf.lite.Interpreter(model_path=self.model_path)`.
